services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: on-failure
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    expose:
      - 443
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - inception
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/luis-ffe/data/mariadb
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/luis-ffe/data/wordpress

networks:
  inception:
    driver: bridge
