
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    expose:
      - 443
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    restart: on-failure
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
networks:
  inception:
    driver: bridge

